/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SearchRouteImport } from './routes/search'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ExclusiveRouteImport } from './routes/exclusive'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsGrowthPacksRouteImport } from './routes/vendors.growth-packs'
import { Route as VendorsDashboardRouteImport } from './routes/vendors.dashboard'
import { Route as VendorSlugRouteImport } from './routes/vendor.$slug'
import { Route as PartySlugRouteImport } from './routes/party.$slug'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveRoute = ExclusiveRouteImport.update({
  id: '/exclusive',
  path: '/exclusive',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsGrowthPacksRoute = VendorsGrowthPacksRouteImport.update({
  id: '/growth-packs',
  path: '/growth-packs',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsDashboardRoute = VendorsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorSlugRoute = VendorSlugRouteImport.update({
  id: '/vendor/$slug',
  path: '/vendor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartySlugRoute = PartySlugRouteImport.update({
  id: '/party/$slug',
  path: '/party/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/board': typeof BoardRoute
  '/calculator': typeof CalculatorRoute
  '/exclusive': typeof ExclusiveRoute
  '/kits': typeof KitsRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/party/$slug': typeof PartySlugRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendors/dashboard': typeof VendorsDashboardRoute
  '/vendors/growth-packs': typeof VendorsGrowthPacksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/board': typeof BoardRoute
  '/calculator': typeof CalculatorRoute
  '/exclusive': typeof ExclusiveRoute
  '/kits': typeof KitsRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/party/$slug': typeof PartySlugRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendors/dashboard': typeof VendorsDashboardRoute
  '/vendors/growth-packs': typeof VendorsGrowthPacksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/board': typeof BoardRoute
  '/calculator': typeof CalculatorRoute
  '/exclusive': typeof ExclusiveRoute
  '/kits': typeof KitsRoute
  '/search': typeof SearchRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/party/$slug': typeof PartySlugRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendors/dashboard': typeof VendorsDashboardRoute
  '/vendors/growth-packs': typeof VendorsGrowthPacksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/board'
    | '/calculator'
    | '/exclusive'
    | '/kits'
    | '/search'
    | '/vendors'
    | '/party/$slug'
    | '/vendor/$slug'
    | '/vendors/dashboard'
    | '/vendors/growth-packs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/board'
    | '/calculator'
    | '/exclusive'
    | '/kits'
    | '/search'
    | '/vendors'
    | '/party/$slug'
    | '/vendor/$slug'
    | '/vendors/dashboard'
    | '/vendors/growth-packs'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/board'
    | '/calculator'
    | '/exclusive'
    | '/kits'
    | '/search'
    | '/vendors'
    | '/party/$slug'
    | '/vendor/$slug'
    | '/vendors/dashboard'
    | '/vendors/growth-packs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BoardRoute: typeof BoardRoute
  CalculatorRoute: typeof CalculatorRoute
  ExclusiveRoute: typeof ExclusiveRoute
  KitsRoute: typeof KitsRoute
  SearchRoute: typeof SearchRoute
  VendorsRoute: typeof VendorsRouteWithChildren
  PartySlugRoute: typeof PartySlugRoute
  VendorSlugRoute: typeof VendorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive': {
      id: '/exclusive'
      path: '/exclusive'
      fullPath: '/exclusive'
      preLoaderRoute: typeof ExclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/growth-packs': {
      id: '/vendors/growth-packs'
      path: '/growth-packs'
      fullPath: '/vendors/growth-packs'
      preLoaderRoute: typeof VendorsGrowthPacksRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/dashboard': {
      id: '/vendors/dashboard'
      path: '/dashboard'
      fullPath: '/vendors/dashboard'
      preLoaderRoute: typeof VendorsDashboardRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendor/$slug': {
      id: '/vendor/$slug'
      path: '/vendor/$slug'
      fullPath: '/vendor/$slug'
      preLoaderRoute: typeof VendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$slug': {
      id: '/party/$slug'
      path: '/party/$slug'
      fullPath: '/party/$slug'
      preLoaderRoute: typeof PartySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VendorsRouteChildren {
  VendorsDashboardRoute: typeof VendorsDashboardRoute
  VendorsGrowthPacksRoute: typeof VendorsGrowthPacksRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsDashboardRoute: VendorsDashboardRoute,
  VendorsGrowthPacksRoute: VendorsGrowthPacksRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BoardRoute: BoardRoute,
  CalculatorRoute: CalculatorRoute,
  ExclusiveRoute: ExclusiveRoute,
  KitsRoute: KitsRoute,
  SearchRoute: SearchRoute,
  VendorsRoute: VendorsRouteWithChildren,
  PartySlugRoute: PartySlugRoute,
  VendorSlugRoute: VendorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
